### ISSUE TITLE
Additional Step: Creating Github Account

### ISSUE THREAD

**Issue by boko91** [cwcromwell/docs#1]
One of our WTD folks needed to create a Github account, and got rerouted to their instructions for Getting Started Using Github. This prevented her from being able to follow through your simpler and more direct instructions, and she found it overwhelming.

Perhaps adding a note to address creating a Github account is necessary to let folks know that they should come back to your instructions.

**Comment by cwcromwell** [comment]
This change is made. 
Je vous remercie!
