### ISSUE TITLE
how about using git commit -m "example change message"?

### ISSUE THREAD

**Issue by irisrogers** [cwcromwell/docs#3]
I use git commit -m "your change here" because it's faster than opening the text editor. 
The syntax is:
git commit -m "example of a change  message"
-m <msg> is the message option,  --message=<msg>
           Use the given <msg> as the commit message. If multiple -m options
           are given, their values are concatenated as separate paragraphs.

**Comment by cwcromwell** [comment]
Thanks, Iris. 
Your suggestion about using git -m was overlooked after the SF Meetup, but I just added it. Thanks for making the page better.
